import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import { MdOutlineDone } from "react-icons/md";
import { BiEditAlt } from "react-icons/bi";
import { useState, useEffect } from "react";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [mainText, setMainText] = useState(
    "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quam amettemporibus blanditiis, id laboriosam sed sapiente, necessitatibusrepellendus repellat voluptatum nostrum eos dolorem? Inventore utblanditiis amet non. Possimus perferendis, culpa qui earum labore,praesentium fugiat cum soluta porro aliquid eius esse dolorum autemnulla, necessitatibus accusantium maiores quam quo."
  );
  const [isOnEdit, setIsOnEdit] = useState(false);
  const [draftText, setDraftText] = useState(mainText);
  const textEditorFunc = () => {
    setIsOnEdit(true);
  };
  const textOnEdit = (e) => {
    setDraftText(e.target.value);
  };
  const submitHandler = () => {
    setMainText(draftText);
    setIsOnEdit(false);
  };
  const editCanceler = () => {
    setIsOnEdit(false);
    setDraftText(mainText);
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,200;0,300;0,400;0,600;0,700;0,800;1,200;1,300&display=swap"
          rel="stylesheet"
        />
      </Head>
      <main
        className={
          isOnEdit
            ? "bg-[#00000064] w-full h-screen pt-20 "
            : "bg-white w-full h-screen pt-20  "
        }
      >
        <div className={isOnEdit ? "blur-lg " : "z-0"}>
          <nav className="w-[40%] shadow-lg p-10 mx-auto flex items-start justify-start rounded-xl shadow-[#afacff] bg-[#8480fc] ">
            <h1 className="text-3xl text-center ">Project Test</h1>
          </nav>
          <section
            className={
              isOnEdit
                ? "hidden"
                : "w-[50%] mt-32 p-6 mx-auto bg-[#d0d0d047] rounded-xl flex items-center justify-center gap-6 flex-col "
            }
          >
            <div className="flex items-center justify-between w-[95%]">
              <h2 className="text-2xl font-semibold ">About</h2>
              <button
                type="button"
                className="p-3 hover:bg-white cursor-pointer hover:text-black text-slate-600 rounded-lg mb-2 "
                onClick={textEditorFunc}
              >
                <BiEditAlt className="text-xl" />
              </button>
            </div>
            <p className="text-justify w-[95%] text-slate-800 ">{mainText}</p>
          </section>
        </div>
        <section
          className={
            isOnEdit
              ? "w-[50%] mt-32 p-6 mx-auto bg-white rounded-xl flex items-center justify-center gap-6 flex-col z-10 "
              : "opacity-0 hidden"
          }
        >
          <div className="flex items-center justify-between w-[95%]">
            <h2 className="text-2xl font-semibold ">About</h2>
            <div className="flex w-[50%] items-center justify-end gap-4 ">
              <button
                onClick={editCanceler}
                type="button"
                className="p-2 px-3 hover:bg-red-100 cursor-pointer text-red-600 rounded-lg "
              >
                Cancel
              </button>
              <button
                type="submit"
                onClick={submitHandler}
                className="p-2 cursor-pointer bg-green-500  text-white rounded-full gap-6 flex items-center justify-between "
              >
                Save
                <MdOutlineDone className="text-2xl border-white border-solid border-[1px] rounded-full p-[1px]  " />
              </button>
            </div>
          </div>
          <textarea
            type="text"
            value={draftText}
            onChange={textOnEdit}
            className="w-full h-52 text-justify outline-none border-b-[1px] border-black "
          />
        </section>
      </main>
    </>
  );
}
